version: '3'
services:
  jupyter_custom:
    build: .
    ports:
      - "8890:8888"
    links:
      - wdb
    environment:
      WDB_SOCKET_SERVER: wdb
      WDB_NO_BROWSER_AUTO_OPEN: "True"

  wdb:
    image: kozea/wdb
    ports:
      - "1984:1984"