---
version: "3.7"
services:
  jupyter_custom:
    container_name: jupyter_custom
    build: .
    ports:
      - "8890:8888"
    environment:
      WDB_SOCKET_SERVER: wdb
      WDB_NO_BROWSER_AUTO_OPEN: "True"
    volumes:
      - "./:/repo:rw"

  wdb:
    image: kozea/wdb
    ports:
      - "1984:1984"

# Default network for containers to communicate together
networks:
  default:
