---
version: "3.7"
services:
  jupyter_custom:
    container_name: jupyter_custom
    build:
      context: .
      args:
        conda_env: "Brown"
    ports:
      - "8888:8888"
    environment:
      WDB_SOCKET_SERVER: wdb
      WDB_NO_BROWSER_AUTO_OPEN: "True"
      RESTARTABLE: "yes"
      # $(id -u)
      NB_UID: 1001
      # id -g
      NB_GID: 1001
      GRANT_SUDO: "yes"
    volumes:
      - ./:/home/jovyan/work/
    user: root

  wdb:
    image: kozea/wdb
    ports:
      - "1984:1984"

# Default network for containers to communicate together
networks:
  default:
