---
version: "3.7"
services:
  jupyter_custom:
    container_name: jupyter_custom
    build:
      context: .
      args:
        conda_env: "Fleischmann"
    ports:
      - "8888:8888"
    environment:
      WDB_SOCKET_SERVER: wdb
      WDB_NO_BROWSER_AUTO_OPEN: "True"
      RESTARTABLE: "yes"
    volumes:
      - "./:/repo:rw"
      # - ./:/home/jovyan/work
      # - /etc/passwd:/etc/passwd:ro
      # - /etc/group:/etc/group:ro

  wdb:
    image: kozea/wdb
    ports:
      - "1984:1984"

# Default network for containers to communicate together
networks:
  default:
