name: xkcd
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - numpy>=1.17.5
  - scipy>=1.4.1
  - ipykernel>=5.1.3
  - pip>=19.3.1
  - matplotlib>=3.1.2
  - nodejs>=13.7.0
  - jupyterlab>=1.2.5
  - jupytext>=1.3.2
  - ipympl>=0.4.1
  - jupyterlab-git>=0.9.0
  - ipdb>=0.12.3
  - black>=19.10b0
  - jupyterlab_code_formatter>=1.0.3
  - flake8>=3.7.9
  - ipywidgets>=7.5.1
  - pytest>=5.3.5
  - pip:
    - ipyfilechooser>=0.3.2
    - wdb.server>=3.3.0